---
overwrite: false
prefer_grub_d: false
keep_distributor: false
kernel_params: [ "quiet", "loglevel=3", "nowatchdog" ]
defaults:
    GRUB_TIMEOUT: 5
    GRUB_DEFAULT: "0"
    GRUB_DISABLE_SUBMENU: false
    GRUB_TERMINAL_OUTPUT: "gfxterm"
    GRUB_DISABLE_RECOVERY: true
always_use_defaults: false
