---
backend: pacman
skip_if_no_internet: true
update_db: true
update_system: false
pacman:
    num_retries: 2
    disable_download_timeout: false
    needed_only: true
operations:
    - try_install:
        - zsh-autosuggestions
        - zsh-syntax-highlighting
        - zsh-completions
