---
units:
    - name: "NetworkManager.service"
      action: "enable"
      mandatory: true
    - name: "systemd-resolved.service"
      action: "enable"
      mandatory: true
    - name: "bluetooth.service"
      action: "enable"
      mandatory: false
    - name: "fstrim.timer"
      action: "enable"
      mandatory: false
    - name: "systemd-timesyncd.service"
      action: "enable"
      mandatory: false
    - name: "power-profiles-daemon.service"
      action: "enable"
      mandatory: false
    - name: "cups.socket"
      action: "enable"
      mandatory: false
    - name: "paccache.timer"
      action: "enable"
      mandatory: false
