---
defaultGroups:
    - users
    - wheel
    - audio
    - video
    - input
    - network
    - storage
    - lp
    - name: autologin
      must_exist: false
      system: true
sudoersGroup: wheel
sudoersConfigureWithGroup: true
autologinGroup: autologin
setRootPassword: true
doReusePassword: true
displayAutologin: true
doAutologin: false
allowWeakPasswords: true
allowWeakPasswordsDefault: false
passwordRequirements:
    minLength: 4
    maxLength: -1
user:
    shell: /bin/bash
    forbidden_names: [ root, liveuser ]
hostname:
    location: EtcFile
    writeHostsFile: true
    template: "auxo-${product}"
    forbidden_names: [ localhost ]
