---
showSupportUrl:      true
showKnownIssuesUrl:  true
showReleaseNotesUrl: true
showDonateUrl:       false

requirements:
    requiredStorage:    20
    requiredRam:        2.0
    internetCheckUrl:
        - https://archlinux.org
        - https://auxolinux.com
    check:
        - storage
        - ram
        - power
        - internet
        - root
        - screen
    required:
        - storage
        - ram
        - root

geoip:
    style:    "json"
    url:      "https://geoip.kde.org/v1/calamares"
    selector: ""
