"""Accent colour engine: one colour, applied everywhere
(GRUB menu, login screen, MOTD, terminals, bars, notifications, KDE/GNOME accents)."""
import os
import shutil

from auxo_accents import ACCENTS, DEFAULT, hex_to_rgb
from auxo_core import (R, DRY, log, run, have, read_conf, write_conf, write_file, set_kv,
                       home_of, chown)
from auxo_desktops import GNOME_ACCENT

WALLDIR = "/usr/share/wallpapers"
GRUB_THEME = "/usr/share/grub/themes/auxo"
SPLASH_SRC = "/usr/share/auxo/plymouth"
SPLASH_THEME = "/usr/share/plymouth/themes/auxo"


def current():
    a = read_conf().get("ACCENT", DEFAULT)
    return a if a in ACCENTS else DEFAULT


def colors(accent):
    a, b = ACCENTS[accent]
    return {"accent": a, "accent2": b, "bg": "#0b0b10", "bg2": "#15151e", "fg": "#e8e8f0",
            "muted": "#6b6b80", "urgent": "#fb7185"}


# ── system level ──────────────────────────────────────────────────────
def grub_theme_txt(c):
    return f'''# Auxo GRUB theme — generated by auxo-tweak, edits will be overwritten
title-text: ""
desktop-image: "background.png"
desktop-image-scale-method: "crop"
desktop-color: "{c['bg']}"
terminal-font: "Unifont Regular 16"
terminal-left: "0"
terminal-top: "0"
terminal-width: "100%"
terminal-height: "100%"
terminal-border: "0"

+ label {{
    top = 12%
    left = 0
    width = 100%
    align = "center"
    text = "auxo"
    color = "{c['accent']}"
    font = "Unifont Regular 16"
}}

+ boot_menu {{
    left = 30%
    top = 34%
    width = 40%
    height = 40%
    item_color = "{c['fg']}"
    selected_item_color = "{c['bg']}"
    item_height = 34
    item_padding = 10
    item_spacing = 6
    icon_width = 0
    icon_height = 0
    selected_item_pixmap_style = "select_*.png"
}}

+ label {{
    top = 82%
    left = 0
    width = 100%
    align = "center"
    id = "__timeout__"
    text = "Booting in %d s  —  ↑↓ choose · e edit · c console"
    color = "{c['muted']}"
    font = "Unifont Regular 16"
}}
'''


def _solid_png(path, rgb):
    """Write a tiny solid-colour PNG without Pillow (used for GRUB selection pixmaps)."""
    import struct
    import zlib
    w = h = 4
    raw = b"".join(b"\x00" + bytes(rgb) * w for _ in range(h))

    def chunk(t, d):
        return struct.pack(">I", len(d)) + t + d + struct.pack(">I", zlib.crc32(t + d) & 0xFFFFFFFF)
    data = b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", struct.pack(">IIBBBBB", w, h, 8, 2, 0, 0, 0)) + \
        chunk(b"IDAT", zlib.compress(raw)) + chunk(b"IEND", b"")
    with open(path, "wb") as f:
        f.write(data)


def apply_grub(accent, mkconfig=True):
    c = colors(accent)
    d = R(GRUB_THEME)
    os.makedirs(d, exist_ok=True)
    wall = R(f"{WALLDIR}/auxo-{accent}.png")
    if os.path.exists(wall):
        shutil.copyfile(wall, os.path.join(d, "background.png"))
    write_file(f"{GRUB_THEME}/theme.txt", grub_theme_txt(c))
    for part in ("c", "n", "s", "e", "w", "ne", "nw", "se", "sw"):
        _solid_png(os.path.join(d, f"select_{part}.png"), hex_to_rgb(c["accent"]))
    if os.path.exists(R("/etc/default/grub")):
        set_kv("/etc/default/grub", "GRUB_THEME", f"{GRUB_THEME}/theme.txt")
        set_kv("/etc/default/grub", "GRUB_GFXMODE", "auto")
        set_kv("/etc/default/grub", "GRUB_TERMINAL_OUTPUT", "gfxterm")
        set_kv("/etc/default/grub", "GRUB_DISTRIBUTOR", "Auxo")
        # GRUB reads theme.txt + background.png at every boot, so an accent change only
        # needs a grub.cfg rebuild the first time the Auxo theme is wired in.
        cfg = R("/boot/grub/grub.cfg")
        wired = os.path.exists(cfg) and f"{GRUB_THEME}/theme.txt" in open(cfg, errors="ignore").read()
        if mkconfig and not wired and have("grub-mkconfig") and os.path.exists(R("/boot/grub")):
            grub_mkconfig()


def grub_mkconfig():
    """Rebuild grub.cfg safely: one run at a time (grub-btrfsd can start its own),
    with a single retry if another run removed grub.cfg.new underneath us."""
    cmd = ["flock", "-w", "120", "/run/lock/auxo-grub.lock", "grub-mkconfig", "-o", "/boot/grub/grub.cfg"]
    if run(cmd, check=False) != 0:
        import time
        time.sleep(3)
        if run(cmd, check=False) != 0:
            log("grub-mkconfig failed — your old boot menu is untouched; run 'sudo grub-mkconfig -o /boot/grub/grub.cfg' to see why")
            return False
    return True


# nearest terminal colour for each accent (tuigreet draws with the 16 ANSI colours)
TUI_COLOR = {"violet": "magenta", "cyan": "cyan", "emerald": "green", "amber": "yellow",
             "rose": "red", "blue": "blue", "mono": "white"}


def greetd_config(accent, cmd=None):
    c = TUI_COLOR.get(accent, "magenta")
    theme = f"border={c};title={c};greet=white;prompt={c};input=white;action={c};button={c};time=darkgray;text=gray"
    args = ["tuigreet", "--time", "--remember", "--remember-user-session",
            "--greeting 'Auxo Linux — climb your own setup'", f"--theme '{theme}'",
            "--sessions /usr/share/wayland-sessions", "--xsessions /usr/share/xsessions",
            "--xsession-wrapper 'startx /usr/bin/env'"]
    if cmd:
        args.append(f"--cmd '{cmd}'")
    command = " ".join(args).replace('"', '\\"')
    return ("# written by auxo-tweak — text login (greetd + tuigreet)\n"
            "[terminal]\nvt = 1\n\n"
            f'[default_session]\ncommand = "{command}"\nuser = "_greeter"\n')


def apply_login(accent):
    """Text login screen (greetd + tuigreet) in the accent colour, starting the chosen desktop."""
    if not (os.path.isdir(R("/etc/greetd")) or os.path.exists(R("/usr/bin/tuigreet"))):
        return
    from auxo_desktops import DESKTOPS
    d = DESKTOPS.get(read_conf().get("DESKTOP", ""), {})
    write_file("/etc/greetd/config.toml", greetd_config(accent, d.get("cmd")))


def apply_sddm(accent):
    """Only used by the live ISO now (installed systems use greetd).
    Never point SDDM at a theme that isn't really installed: a Breeze folder without
    metadata.desktop makes SDDM try a greeter that isn't installed → black screen."""
    if not os.path.exists(R("/usr/bin/sddm")):
        return
    wall = f"{WALLDIR}/auxo-{accent}.png"
    if os.path.exists(R("/usr/bin/kwin_wayland")):
        server = ("[General]\nDisplayServer=wayland\nGreeterEnvironment=QT_WAYLAND_SHELL_INTEGRATION=layer-shell\nInputMethod=\n\n"
                  "[Wayland]\nCompositorCommand=kwin_wayland --drm --no-lockscreen --no-global-shortcuts --locale1\n\n")
    else:
        server = "[General]\nDisplayServer=x11\nInputMethod=\n\n"
    breeze = R("/usr/share/sddm/themes/breeze/metadata.desktop")
    theme = "[Theme]\nCurrent=breeze\nCursorTheme=breeze_cursors\n" if os.path.exists(breeze) else "[Theme]\nCurrent=\n"
    write_file("/etc/sddm.conf.d/10-auxo.conf", server + theme)
    if os.path.exists(breeze):
        write_file("/usr/share/sddm/themes/breeze/theme.conf.user", f"[General]\nbackground={wall}\ntype=image\n")


def motd(accent):
    r, g, b = hex_to_rgb(ACCENTS[accent][0])
    r2, g2, b2 = hex_to_rgb(ACCENTS[accent][1])
    c1, c2, rs = f"\033[38;2;{r};{g};{b}m", f"\033[38;2;{r2};{g2};{b2}m", "\033[0m"
    return (f"\n{c1}      /\\       {rs}\033[1mAuxo Linux{rs}  —  climb your own setup\n"
            f"{c1}     /  \\      {rs}  auxo-tweak   change accent, kernel, desktop, shell\n"
            f"{c2}    / /\\ \\     {rs}  auxo-update  snapshot + update everything\n"
            f"{c2}   /_/  \\_\\    {rs}  auxo-fetch   system summary\n\n")


def apply_splash(accent):
    """Copy the Plymouth theme + this accent's images into place.
    Returns True when anything changed (the initramfs then needs a rebuild)."""
    import filecmp
    src_theme, src_acc = R(f"{SPLASH_SRC}/theme"), R(f"{SPLASH_SRC}/accents/{accent}")
    if not os.path.isdir(src_theme) or not os.path.isdir(src_acc):
        return False
    dst = R(SPLASH_THEME)
    os.makedirs(dst, exist_ok=True)
    changed = False
    for d in (src_theme, src_acc):
        for f in sorted(os.listdir(d)):
            a, b = os.path.join(d, f), os.path.join(dst, f)
            if not os.path.exists(b) or not filecmp.cmp(a, b, shallow=False):
                shutil.copyfile(a, b)
                changed = True
    return changed


def apply_system(accent, mkconfig=True):
    if accent not in ACCENTS:
        raise ValueError(f"unknown accent '{accent}'. choose: {', '.join(ACCENTS)}")
    write_conf({"ACCENT": accent})
    apply_grub(accent, mkconfig)
    apply_sddm(accent)
    apply_login(accent)
    write_file("/etc/motd", motd(accent))
    splash_changed = apply_splash(accent)
    import auxo_kde
    auxo_kde.apply_system(accent)
    log(f"system accent → {accent} ({ACCENTS[accent][0]})")
    return splash_changed


# ── per-user ──────────────────────────────────────────────────────────
def user_color_files(accent):
    c = colors(accent)
    a, a2 = c["accent"].lstrip("#"), c["accent2"].lstrip("#")
    r, g, b = hex_to_rgb(c["accent"])
    return {
        "colors.css": "".join(f"@define-color {k} {v};\n" for k, v in c.items()),
        "colors-hyprland.conf": f"$accent = rgb({a})\n$accent2 = rgb({a2})\n$inactive = rgba(2a2a38aa)\n",  # hyprlock
        "hypr_colors.lua": f'-- generated by auxo-tweak\nreturn {{ accent = "rgb({a})", accent2 = "rgb({a2})", inactive = "rgba(2a2a38aa)" }}\n',  # hyprland.lua
        "colors-sway": f"set $accent {c['accent']}\nset $accent2 {c['accent2']}\nset $bg {c['bg']}\nset $fg {c['fg']}\nset $muted {c['muted']}\n",
        "colors-i3": f"set $accent {c['accent']}\nset $accent2 {c['accent2']}\nset $bg {c['bg']}\nset $fg {c['fg']}\nset $muted {c['muted']}\n",
        "colors-polybar.ini": "[auxo]\n" + "".join(f"{k} = {v}\n" for k, v in c.items()),
        "colors.rasi": "* {\n" + "".join(f"    {k}: {v};\n" for k, v in c.items()) + "}\n",
        "colors-kitty.conf": f"background {c['bg']}\nforeground {c['fg']}\ncursor {c['accent']}\nselection_background {c['accent']}\n"
                             f"selection_foreground {c['bg']}\nactive_border_color {c['accent']}\nactive_tab_background {c['accent']}\n"
                             f"active_tab_foreground {c['bg']}\ncolor5 {c['accent']}\ncolor13 {c['accent']}\ncolor6 {c['accent2']}\ncolor14 {c['accent2']}\n",
        "colors-foot.ini": f"[colors]\nbackground={c['bg'].lstrip('#')}\nforeground={c['fg'].lstrip('#')}\n"
                           f"regular5={a}\nbright5={a}\nregular6={a2}\nbright6={a2}\nselection-background={a}\nselection-foreground={c['bg'].lstrip('#')}\n",
        "colors-alacritty.toml": f"[colors.primary]\nbackground = \"{c['bg']}\"\nforeground = \"{c['fg']}\"\n"
                                 f"[colors.cursor]\ncursor = \"{c['accent']}\"\n[colors.normal]\nmagenta = \"{c['accent']}\"\ncyan = \"{c['accent2']}\"\n"
                                 f"[colors.bright]\nmagenta = \"{c['accent']}\"\ncyan = \"{c['accent2']}\"\n",
        "dunst.conf": f"[global]\nframe_color = \"{c['accent']}\"\n[urgency_normal]\nbackground = \"{c['bg2']}\"\nforeground = \"{c['fg']}\"\n",
        "accent": f"{accent}\n{c['accent']}\n{r},{g},{b}\n",
    }


def mako_config(accent):
    c = colors(accent)
    return (f"# generated by auxo-tweak\nfont=Inter 11\nbackground-color={c['bg2']}ee\ntext-color={c['fg']}\n"
            f"border-color={c['accent']}\nborder-size=2\nborder-radius=10\npadding=12\nwidth=360\ndefault-timeout=6000\n"
            f"[urgency=high]\nborder-color={c['urgent']}\n")


def apply_user(user, accent):
    home = home_of(user)
    cfg = f"{home}/.config/auxo"
    for name, content in user_color_files(accent).items():
        write_file(f"{cfg}/{name}", content)
    # the rices point at ~/.config/auxo/wallpaper.png
    link = R(f"{cfg}/wallpaper.png")
    if os.path.lexists(link):
        os.remove(link)
    os.symlink(f"{WALLDIR}/auxo-{accent}.png", link)
    if os.path.isdir(R(f"{home}/.config/mako")):
        write_file(f"{home}/.config/mako/config", mako_config(accent))
    if os.path.isdir(R(f"{home}/.config/dunst")):
        os.makedirs(R(f"{home}/.config/dunst/dunstrc.d"), exist_ok=True)
        shutil.copyfile(R(f"{cfg}/dunst.conf"), R(f"{home}/.config/dunst/dunstrc.d/50-auxo.conf"))
    # KDE: Auxo global theme + colours with this accent (right from the first login)
    import auxo_kde
    auxo_kde.merge_kdeglobals(f"{home}/.config/kdeglobals", accent)
    # one-shot autostart that pushes wallpaper/accent into whatever desktop starts next
    write_file(f"{home}/.config/autostart/auxo-session-apply.desktop",
               "[Desktop Entry]\nType=Application\nName=Auxo accent\nExec=auxo-tweak session-apply --once\n"
               "NoDisplay=true\nX-GNOME-Autostart-enabled=true\n")
    chown(f"{home}/.config", user, recursive=True)
    log(f"{user}: accent → {accent}")


def _ini_set(path, section, key, value):
    lines = open(path).read().splitlines() if os.path.exists(path) else []
    out, in_sec, done, found_sec = [], False, False, False
    for line in lines:
        s = line.strip()
        if s.startswith("[") and s.endswith("]"):
            if in_sec and not done:
                out.append(f"{key}={value}")
                done = True
            in_sec = s[1:-1] == section
            found_sec = found_sec or in_sec
        elif in_sec and s.split("=", 1)[0] == key:
            if not done:
                out.append(f"{key}={value}")
                done = True
            continue
        out.append(line)
    if not found_sec:
        out += ["", f"[{section}]"]
    if not done:
        out.append(f"{key}={value}")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write("\n".join(out).lstrip("\n") + "\n")


# process name → XDG_CURRENT_DESKTOP, in detection order
SESSION_PROCS = [("plasmashell", "KDE"), ("gnome-shell", "GNOME"), ("cinnamon", "X-Cinnamon"),
                 ("xfce4-session", "XFCE"), ("Hyprland", "Hyprland"), ("sway", "sway"), ("i3", "i3")]


def session_env(user):
    """Environment for talking to `user`'s running graphical session (or None).
    Built from /run/user/<uid> and the running processes, because sudo strips
    DISPLAY / WAYLAND_DISPLAY / DBUS_SESSION_BUS_ADDRESS."""
    import glob
    import pwd
    if DRY:
        return None
    try:
        pw = pwd.getpwnam(user)
    except KeyError:
        return None
    rt = f"/run/user/{pw.pw_uid}"
    if not os.path.isdir(rt):
        return None
    procs = set((run(["ps", "-u", str(pw.pw_uid), "-o", "comm="], capture=True, check=False) or "").split())
    desk = next((d for p, d in SESSION_PROCS if p in procs), None)
    if not desk:
        return None
    env = {"XDG_RUNTIME_DIR": rt, "HOME": pw.pw_dir, "USER": user, "LOGNAME": user,
           "XDG_CURRENT_DESKTOP": desk}
    if os.path.exists(f"{rt}/bus"):
        env["DBUS_SESSION_BUS_ADDRESS"] = f"unix:path={rt}/bus"
    way = sorted(p for p in glob.glob(f"{rt}/wayland-*") if not p.endswith(".lock"))
    if way:
        env["WAYLAND_DISPLAY"] = os.path.basename(way[0])
    xs = sorted(glob.glob("/tmp/.X11-unix/X*"))
    if xs:
        env["DISPLAY"] = ":" + xs[0].rsplit("X", 1)[1]
        xa = os.path.join(pw.pw_dir, ".Xauthority")
        if os.path.exists(xa):
            env["XAUTHORITY"] = xa
    hy = sorted(glob.glob(f"{rt}/hypr/*/.socket.sock"), key=os.path.getmtime)
    if hy:
        env["HYPRLAND_INSTANCE_SIGNATURE"] = os.path.basename(os.path.dirname(hy[-1]))
    sw = sorted(glob.glob(f"{rt}/sway-ipc.*.sock"), key=os.path.getmtime)
    if sw:
        env["SWAYSOCK"] = sw[-1]
    return env


def _spawn(cmd):
    """Start a long-running helper (wallpaper daemon) detached from us."""
    import subprocess
    if DRY:
        print("[dry-run] " + " ".join(cmd) + " &", flush=True)
        return
    try:
        subprocess.Popen(cmd, stdin=subprocess.DEVNULL, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
                         start_new_session=True)
    except OSError:
        pass


def session_apply(accent=None, once=False):
    """Run inside a graphical session: push accent + wallpaper to the live desktop."""
    accent = accent or current()
    wall = f"{WALLDIR}/auxo-{accent}.png"
    a = ACCENTS[accent][0]
    de = os.environ.get("XDG_CURRENT_DESKTOP", "").lower()
    if "kde" in de:
        if have("plasma-apply-colorscheme"):
            scheme = "AuxoDark" if os.path.exists("/usr/share/color-schemes/AuxoDark.colors") or DRY else "BreezeDark"
            run(["plasma-apply-colorscheme", "--accent-color", a, scheme], check=False)
        if have("plasma-apply-wallpaperimage"):
            run(["plasma-apply-wallpaperimage", wall], check=False)
    elif "gnome" in de and have("gsettings"):
        for key in ("picture-uri", "picture-uri-dark"):
            run(["gsettings", "set", "org.gnome.desktop.background", key, f"file://{wall}"], check=False)
        run(["gsettings", "set", "org.gnome.desktop.background", "picture-options", "zoom"], check=False)
        run(["gsettings", "set", "org.gnome.desktop.screensaver", "picture-uri", f"file://{wall}"], check=False)
        run(["gsettings", "set", "org.gnome.desktop.interface", "color-scheme", "prefer-dark"], check=False)
        run(["gsettings", "set", "org.gnome.desktop.interface", "accent-color", GNOME_ACCENT[accent]], check=False)
    elif "cinnamon" in de and have("gsettings"):
        run(["gsettings", "set", "org.cinnamon.desktop.background", "picture-uri", f"file://{wall}"], check=False)
        run(["gsettings", "set", "org.cinnamon.desktop.background", "picture-options", "zoom"], check=False)
    elif "xfce" in de and have("xfconf-query"):
        props = [p for p in (run(["xfconf-query", "-c", "xfce4-desktop", "-l"], capture=True, check=False) or "").split()
                 if p.endswith("/last-image")]
        for p in props or ["/backdrop/screen0/monitor0/workspace0/last-image"]:
            run(["xfconf-query", "-c", "xfce4-desktop", "-p", p, "--create", "-t", "string", "-s", wall], check=False)
    elif "hyprland" in de:
        # hyprpaper keeps the old image in memory: restart it on the new wallpaper
        run(["pkill", "-x", "hyprpaper"], check=False)
        # let Hyprland start it (so it lives in the session); detach it ourselves as a fallback
        if have("hyprpaper") and not (have("hyprctl") and run(["hyprctl", "dispatch", "exec", "hyprpaper"], check=False) == 0):
            _spawn(["hyprpaper"])
        if have("hyprctl"):
            run(["hyprctl", "reload"], check=False)
        run(["pkill", "-SIGUSR2", "waybar"], check=False)
        run(["makoctl", "reload"], check=False)
    elif "sway" in de and have("swaymsg"):
        run(["swaymsg", "reload"], check=False)
        run(["swaymsg", "output", "*", "bg", wall, "fill"], check=False)
        run(["makoctl", "reload"], check=False)
    elif "i3" in de:
        if have("feh"):
            run(["feh", "--no-fehbg", "--bg-fill", wall], check=False)
        if have("i3-msg"):
            run(["i3-msg", "restart"], check=False)
    if once:
        p = os.path.expanduser("~/.config/autostart/auxo-session-apply.desktop")
        if os.path.exists(p) and not DRY:
            os.remove(p)
