"""Accent colour engine: one colour, applied everywhere
(GRUB menu, login screen, MOTD, terminals, bars, notifications, KDE/GNOME accents)."""
import os
import shutil

from auxo_accents import ACCENTS, DEFAULT, hex_to_rgb
from auxo_core import (R, DRY, log, run, have, read_conf, write_conf, write_file, set_kv,
                       home_of, chown)
from auxo_desktops import GNOME_ACCENT

WALLDIR = "/usr/share/wallpapers"
GRUB_THEME = "/usr/share/grub/themes/auxo"


def current():
    a = read_conf().get("ACCENT", DEFAULT)
    return a if a in ACCENTS else DEFAULT


def colors(accent):
    a, b = ACCENTS[accent]
    return {"accent": a, "accent2": b, "bg": "#0b0b10", "bg2": "#15151e", "fg": "#e8e8f0",
            "muted": "#6b6b80", "urgent": "#fb7185"}


# ── system level ──────────────────────────────────────────────────────
def grub_theme_txt(c):
    return f'''# Auxo GRUB theme — generated by auxo-tweak, edits will be overwritten
title-text: ""
desktop-image: "background.png"
desktop-image-scale-method: "crop"
desktop-color: "{c['bg']}"
terminal-font: "Unifont Regular 16"
terminal-left: "0"
terminal-top: "0"
terminal-width: "100%"
terminal-height: "100%"
terminal-border: "0"

+ label {{
    top = 12%
    left = 0
    width = 100%
    align = "center"
    text = "auxo"
    color = "{c['accent']}"
    font = "Unifont Regular 16"
}}

+ boot_menu {{
    left = 30%
    top = 34%
    width = 40%
    height = 40%
    item_color = "{c['fg']}"
    selected_item_color = "{c['bg']}"
    item_height = 34
    item_padding = 10
    item_spacing = 6
    icon_width = 0
    icon_height = 0
    selected_item_pixmap_style = "select_*.png"
}}

+ label {{
    top = 82%
    left = 0
    width = 100%
    align = "center"
    id = "__timeout__"
    text = "Booting in %d s  —  ↑↓ choose · e edit · c console"
    color = "{c['muted']}"
    font = "Unifont Regular 16"
}}
'''


def _solid_png(path, rgb):
    """Write a tiny solid-colour PNG without Pillow (used for GRUB selection pixmaps)."""
    import struct
    import zlib
    w = h = 4
    raw = b"".join(b"\x00" + bytes(rgb) * w for _ in range(h))

    def chunk(t, d):
        return struct.pack(">I", len(d)) + t + d + struct.pack(">I", zlib.crc32(t + d) & 0xFFFFFFFF)
    data = b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", struct.pack(">IIBBBBB", w, h, 8, 2, 0, 0, 0)) + \
        chunk(b"IDAT", zlib.compress(raw)) + chunk(b"IEND", b"")
    with open(path, "wb") as f:
        f.write(data)


def apply_grub(accent, mkconfig=True):
    c = colors(accent)
    d = R(GRUB_THEME)
    os.makedirs(d, exist_ok=True)
    wall = R(f"{WALLDIR}/auxo-{accent}.png")
    if os.path.exists(wall):
        shutil.copyfile(wall, os.path.join(d, "background.png"))
    write_file(f"{GRUB_THEME}/theme.txt", grub_theme_txt(c))
    for part in ("c", "n", "s", "e", "w", "ne", "nw", "se", "sw"):
        _solid_png(os.path.join(d, f"select_{part}.png"), hex_to_rgb(c["accent"]))
    if os.path.exists(R("/etc/default/grub")):
        set_kv("/etc/default/grub", "GRUB_THEME", f"{GRUB_THEME}/theme.txt")
        set_kv("/etc/default/grub", "GRUB_GFXMODE", "auto")
        set_kv("/etc/default/grub", "GRUB_TERMINAL_OUTPUT", "gfxterm")
        set_kv("/etc/default/grub", "GRUB_DISTRIBUTOR", "Auxo")
        if mkconfig and have("grub-mkconfig") and os.path.exists(R("/boot/grub")):
            run(["grub-mkconfig", "-o", "/boot/grub/grub.cfg"], check=False)


def apply_sddm(accent):
    wall = f"{WALLDIR}/auxo-{accent}.png"
    if os.path.exists(R("/usr/bin/kwin_wayland")):
        # Plasma present: Wayland greeter running on KWin
        server = ("[General]\nDisplayServer=wayland\nGreeterEnvironment=QT_WAYLAND_SHELL_INTEGRATION=layer-shell\nInputMethod=\n\n"
                  "[Wayland]\nCompositorCommand=kwin_wayland --drm --no-lockscreen --no-global-shortcuts --locale1\n\n")
    else:
        server = "[General]\nDisplayServer=x11\nInputMethod=\n\n"
    write_file("/etc/sddm.conf.d/10-auxo.conf", server + "[Theme]\nCurrent=breeze\nCursorTheme=breeze_cursors\n")
    if os.path.isdir(R("/usr/share/sddm/themes/breeze")):
        write_file("/usr/share/sddm/themes/breeze/theme.conf.user", f"[General]\nbackground={wall}\ntype=image\n")


def motd(accent):
    r, g, b = hex_to_rgb(ACCENTS[accent][0])
    r2, g2, b2 = hex_to_rgb(ACCENTS[accent][1])
    c1, c2, rs = f"\033[38;2;{r};{g};{b}m", f"\033[38;2;{r2};{g2};{b2}m", "\033[0m"
    return (f"\n{c1}      /\\       {rs}\033[1mAuxo Linux{rs}  —  climb your own setup\n"
            f"{c1}     /  \\      {rs}  auxo-tweak   change accent, kernel, desktop, shell\n"
            f"{c2}    / /\\ \\     {rs}  auxo-update  snapshot + update everything\n"
            f"{c2}   /_/  \\_\\    {rs}  auxo-fetch   system summary\n\n")


def apply_system(accent, mkconfig=True):
    if accent not in ACCENTS:
        raise ValueError(f"unknown accent '{accent}'. choose: {', '.join(ACCENTS)}")
    write_conf({"ACCENT": accent})
    apply_grub(accent, mkconfig)
    apply_sddm(accent)
    write_file("/etc/motd", motd(accent))
    log(f"system accent → {accent} ({ACCENTS[accent][0]})")


# ── per-user ──────────────────────────────────────────────────────────
def user_color_files(accent):
    c = colors(accent)
    a, a2 = c["accent"].lstrip("#"), c["accent2"].lstrip("#")
    r, g, b = hex_to_rgb(c["accent"])
    return {
        "colors.css": "".join(f"@define-color {k} {v};\n" for k, v in c.items()),
        "colors-hyprland.conf": f"$accent = rgb({a})\n$accent2 = rgb({a2})\n$inactive = rgba(2a2a38aa)\n",
        "colors-sway": f"set $accent {c['accent']}\nset $accent2 {c['accent2']}\nset $bg {c['bg']}\nset $fg {c['fg']}\nset $muted {c['muted']}\n",
        "colors-i3": f"set $accent {c['accent']}\nset $accent2 {c['accent2']}\nset $bg {c['bg']}\nset $fg {c['fg']}\nset $muted {c['muted']}\n",
        "colors-polybar.ini": "[auxo]\n" + "".join(f"{k} = {v}\n" for k, v in c.items()),
        "colors.rasi": "* {\n" + "".join(f"    {k}: {v};\n" for k, v in c.items()) + "}\n",
        "colors-kitty.conf": f"background {c['bg']}\nforeground {c['fg']}\ncursor {c['accent']}\nselection_background {c['accent']}\n"
                             f"selection_foreground {c['bg']}\nactive_border_color {c['accent']}\nactive_tab_background {c['accent']}\n"
                             f"active_tab_foreground {c['bg']}\ncolor5 {c['accent']}\ncolor13 {c['accent']}\ncolor6 {c['accent2']}\ncolor14 {c['accent2']}\n",
        "colors-foot.ini": f"[colors]\nbackground={c['bg'].lstrip('#')}\nforeground={c['fg'].lstrip('#')}\n"
                           f"regular5={a}\nbright5={a}\nregular6={a2}\nbright6={a2}\nselection-background={a}\nselection-foreground={c['bg'].lstrip('#')}\n",
        "colors-alacritty.toml": f"[colors.primary]\nbackground = \"{c['bg']}\"\nforeground = \"{c['fg']}\"\n"
                                 f"[colors.cursor]\ncursor = \"{c['accent']}\"\n[colors.normal]\nmagenta = \"{c['accent']}\"\ncyan = \"{c['accent2']}\"\n"
                                 f"[colors.bright]\nmagenta = \"{c['accent']}\"\ncyan = \"{c['accent2']}\"\n",
        "dunst.conf": f"[global]\nframe_color = \"{c['accent']}\"\n[urgency_normal]\nbackground = \"{c['bg2']}\"\nforeground = \"{c['fg']}\"\n",
        "accent": f"{accent}\n{c['accent']}\n{r},{g},{b}\n",
    }


def mako_config(accent):
    c = colors(accent)
    return (f"# generated by auxo-tweak\nfont=Inter 11\nbackground-color={c['bg2']}ee\ntext-color={c['fg']}\n"
            f"border-color={c['accent']}\nborder-size=2\nborder-radius=10\npadding=12\nwidth=360\ndefault-timeout=6000\n"
            f"[urgency=high]\nborder-color={c['urgent']}\n")


def apply_user(user, accent):
    home = home_of(user)
    cfg = f"{home}/.config/auxo"
    for name, content in user_color_files(accent).items():
        write_file(f"{cfg}/{name}", content)
    # the rices point at ~/.config/auxo/wallpaper.png
    link = R(f"{cfg}/wallpaper.png")
    if os.path.lexists(link):
        os.remove(link)
    os.symlink(f"{WALLDIR}/auxo-{accent}.png", link)
    if os.path.isdir(R(f"{home}/.config/mako")):
        write_file(f"{home}/.config/mako/config", mako_config(accent))
    if os.path.isdir(R(f"{home}/.config/dunst")):
        os.makedirs(R(f"{home}/.config/dunst/dunstrc.d"), exist_ok=True)
        shutil.copyfile(R(f"{cfg}/dunst.conf"), R(f"{home}/.config/dunst/dunstrc.d/50-auxo.conf"))
    # KDE: accent + dark scheme are picked up at next login
    r, g, b = hex_to_rgb(ACCENTS[accent][0])
    kg = R(f"{home}/.config/kdeglobals")
    _ini_set(kg, "General", "AccentColor", f"{r},{g},{b}")
    _ini_set(kg, "General", "ColorScheme", "BreezeDark")
    _ini_set(kg, "KDE", "LookAndFeelPackage", "org.kde.breezedark.desktop")
    # one-shot autostart that pushes wallpaper/accent into whatever desktop starts next
    write_file(f"{home}/.config/autostart/auxo-session-apply.desktop",
               "[Desktop Entry]\nType=Application\nName=Auxo accent\nExec=auxo-tweak session-apply --once\n"
               "NoDisplay=true\nX-GNOME-Autostart-enabled=true\n")
    chown(f"{home}/.config", user, recursive=True)
    log(f"{user}: accent → {accent}")


def _ini_set(path, section, key, value):
    lines = open(path).read().splitlines() if os.path.exists(path) else []
    out, in_sec, done, found_sec = [], False, False, False
    for line in lines:
        s = line.strip()
        if s.startswith("[") and s.endswith("]"):
            if in_sec and not done:
                out.append(f"{key}={value}")
                done = True
            in_sec = s[1:-1] == section
            found_sec = found_sec or in_sec
        elif in_sec and s.split("=", 1)[0] == key:
            if not done:
                out.append(f"{key}={value}")
                done = True
            continue
        out.append(line)
    if not found_sec:
        out += ["", f"[{section}]"]
    if not done:
        out.append(f"{key}={value}")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write("\n".join(out).lstrip("\n") + "\n")


def session_apply(accent=None, once=False):
    """Run inside a graphical session: push accent + wallpaper to the live desktop."""
    accent = accent or current()
    wall = f"{WALLDIR}/auxo-{accent}.png"
    a = ACCENTS[accent][0]
    de = os.environ.get("XDG_CURRENT_DESKTOP", "").lower()
    if "kde" in de and have("plasma-apply-colorscheme"):
        run(["plasma-apply-colorscheme", "--accent-color", a, "BreezeDark"], check=False)
        run(["plasma-apply-wallpaperimage", wall], check=False)
    elif "gnome" in de and have("gsettings"):
        for key in ("picture-uri", "picture-uri-dark"):
            run(["gsettings", "set", "org.gnome.desktop.background", key, f"file://{wall}"], check=False)
        run(["gsettings", "set", "org.gnome.desktop.interface", "color-scheme", "prefer-dark"], check=False)
        run(["gsettings", "set", "org.gnome.desktop.interface", "accent-color", GNOME_ACCENT[accent]], check=False)
    elif "cinnamon" in de and have("gsettings"):
        run(["gsettings", "set", "org.cinnamon.desktop.background", "picture-uri", f"file://{wall}"], check=False)
    elif "xfce" in de and have("xfconf-query"):
        props = run(["xfconf-query", "-c", "xfce4-desktop", "-l"], capture=True, check=False) or ""
        for p in props.split():
            if p.endswith("/last-image"):
                run(["xfconf-query", "-c", "xfce4-desktop", "-p", p, "-s", wall], check=False)
    elif "hyprland" in de and have("hyprctl"):
        run(["hyprctl", "reload"], check=False)
        run(["pkill", "-SIGUSR2", "waybar"], check=False)
        run(["makoctl", "reload"], check=False)
    elif "sway" in de and have("swaymsg"):
        run(["swaymsg", "reload"], check=False)
        run(["makoctl", "reload"], check=False)
    elif "i3" in de and have("i3-msg"):
        run(["i3-msg", "restart"], check=False)
    if once:
        p = os.path.expanduser("~/.config/autostart/auxo-session-apply.desktop")
        if os.path.exists(p) and not DRY:
            os.remove(p)
