backend = "glx";
vsync = true;
corner-radius = 12;
shadow = true;
shadow-radius = 16;
shadow-opacity = 0.45;
fading = true;
fade-delta = 5;
inactive-opacity = 0.95;
rounded-corners-exclude = [ "class_g = 'Polybar'" ];
